[package]
name = "arewefastyet"
version = "0.1.0"
authors = ["Krishna Sundarram <krishna.sundarram@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"